name: Build Image

on:
  workflow_dispatch:

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      # Docker Image 构建环境
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3 
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set Version
        id: set-version
        run: |
          TAG=$(wget --no-check-certificate -qO- https://api.github.com/repos/emikulic/darkhttpd/tags | grep 'name' | cut -d\" -f4 | head -1 )
          echo "LatestReleaseTag=${TAG#v}"
          echo "version=${TAG#v}" >> $GITHUB_OUTPUT
          echo "status=success" >> $GITHUB_OUTPUT

      # Build and push
      - name: Build dockerfile
        if: steps.set-version.outputs.status == 'success'
        uses: docker/build-push-action@v6
        with:
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm/v7,linux/arm64,linux/386
          push: true
          tags: |
            antman666/darkhttpd:${{ steps.set-version.outputs.version }}
            antman666/darkhttpd:latest
